### ISSUE TITLE
Extra post glitch.

### ISSUE THREAD

**Issue by buffsheep** [face-hh/lyntr#85] opened 2024-08-07 07:46 UTC
Sometimes you can see multiple of the same post all in a row. Even if they only lynted one time.
![image](https://github.com/user-attachments/assets/f20e49c8-1934-46b4-bb31-e8cf424fd33e)

**Comment by face-hh** [comment] 2024-08-09 07:45
Duplicate of #35

**Closed by face-hh** 2024-08-09 07:45 UTC
