### ISSUE TITLE
Outage weird help

### ISSUE THREAD

**Issue by ali-kingX** [face-hh/lyntr#36] opened 2024-08-05 19:23 UTC
![image](https://github.com/user-attachments/assets/e3ff8a6d-c782-4099-9973-3c926ef5bd91)
![image](https://github.com/user-attachments/assets/46f1e4b1-3747-4498-b03c-e2af8d317f0e)
![image](https://github.com/user-attachments/assets/26de4437-cfe3-4679-afe2-9df0984fb2ca)
![image](https://github.com/user-attachments/assets/d3ceccd1-d63e-44f5-9698-cf72ec22b686)
So many issues...

**Comment by face-hh** [comment] 2024-08-05 19:39
Duplicate of #27

**Closed by face-hh** 2024-08-05 19:39 UTC
