### ISSUE TITLE
Alternative login methods

### ISSUE THREAD

**Issue by everypizza1** [face-hh/lyntr#65] opened 2024-08-06 18:13 UTC
## Summary
It would be nice to have ways to login aside from Discord. For example, Codeberg or traditional email/password login. 

## Motivation
Discord is proprietary/unfree software, which is not the best for an open-source program.

**Comment by face-hh** [comment] 2024-08-09 07:41
Duplicate of #6

**Closed by face-hh** 2024-08-09 07:41 UTC
