### ISSUE TITLE
Feature: Add open graph protocol (or equivalent) to support rich embeds on multiple platforms

### ISSUE THREAD

**Issue by sergeant-savage** [face-hh/lyntr#103] opened 2024-08-08 20:09 UTC
Competing platforms (namely X, but also Reddit), make use of the Open Graph Protocol or analog to create richer embeds on other platforms. I think that adding a similar feature to Lyntr would be a good idea, as it would help create parity between the two, and allow for Lyntr posts to be embedded with feature parity to X posts. 

2 possible options for this feature are the [OpenGraph Protocol](https://ogp.me/), utilized by Meta, and the [Twitter card protocol](https://developer.x.com/en/docs/twitter-for-websites/cards/overview/markup), used by X.

This can be implemented by simply generating the correct information, and adding it to the head tag. Here is an example of Open Graph:
```html
<meta property="og:title" content="The Rock" />
<meta property="og:type" content="video.movie" />
<meta property="og:url" content="https://www.imdb.com/title/tt0117500/" />
<meta property="og:description" content="Goofy ahh movie" />
<meta property="og:image" content="https://ia.media-imdb.com/images/rock.jpg" />
```

**Comment by face-hh** [comment] 2024-08-09 07:49
Duplicate of #96. It's being worked on :+1:

**Closed by face-hh** 2024-08-09 07:49 UTC
