### ISSUE TITLE
[feature request] feedback for posting + allow scrolling while posting

### ISSUE THREAD

**Issue by sweglord227** [face-hh/lyntr#53] opened 2024-08-06 07:30 UTC
posting lints should not force you to continue looking at the lint being uploaded with no feedback. grey out the button, add a loading circle, pin posting to the top of the feed, and/or some other changes. currently it feels very weird and makes me feel unsure on if my lynt is actually posting or not

**Comment by face-hh** [comment] 2024-08-09 07:38
Duplicate of #35

**Closed by face-hh** 2024-08-09 07:38 UTC
